/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzlegame;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexanderNielsen
 */
public class PuzzleGUI extends javax.swing.JFrame {

    /**
     * Creates new form PuzzleGUI
     */
    public PuzzleGUI() {
        initComponents();
        setSize(800, 600);                 // Sets the default size to 500x500
        getContentPane().setBackground(new Color(48, 105, 150));
        setLocationRelativeTo(null);       // Puts the app in the middle
        jButton9.setVisible(false);
        setTitle("PuzzleGame");
        setIcons();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 105, 150));

        jPanel1.setMaximumSize(new java.awt.Dimension(166, 166));
        jPanel1.setMinimumSize(new java.awt.Dimension(166, 166));
        jPanel1.setSize(new java.awt.Dimension(166, 166));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton10.setText("Solve");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jButton9.isVisible()==false){
            jButton9.setText(jButton6.getText());
            jButton9.setIcon(jButton6.getIcon());
            jButton6.setVisible(false);
            jButton9.setVisible(true);
        }
        if(jButton3.isVisible()==false){
            jButton3.setText(jButton6.getText());
            jButton3.setIcon(jButton6.getIcon());
            jButton6.setVisible(false);
            jButton3.setVisible(true);
        }
        if(jButton5.isVisible()==false){
            jButton5.setText(jButton6.getText());
            jButton5.setIcon(jButton6.getIcon());
            jButton6.setVisible(false);
            jButton5.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jButton9.isVisible()==false){
            jButton9.setText(jButton8.getText()); 
            jButton9.setIcon(jButton8.getIcon());
            jButton8.setVisible(false); 
            jButton9.setVisible(true);  
        }
        if(jButton7.isVisible()==false){
            jButton7.setText(jButton8.getText());
            jButton7.setIcon(jButton8.getIcon());
            jButton8.setVisible(false); 
            jButton7.setVisible(true);  
        }
        if(jButton5.isVisible()==false){
            jButton5.setText(jButton8.getText()); 
            jButton5.setIcon(jButton8.getIcon());
            jButton8.setVisible(false); 
            jButton5.setVisible(true);  
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jButton6.isVisible() == false){
        jButton6.setText(jButton9.getText());
        jButton6.setIcon(jButton9.getIcon());
        jButton9.setVisible(false);
        jButton6.setVisible(true);
        }
        if (jButton8.isVisible() == false){
        jButton8.setText(jButton9.getText());
        jButton8.setIcon(jButton9.getIcon());
        jButton9.setVisible(false);
        jButton8.setVisible(true);
        }
        puzzleDone();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jButton8.isVisible()==false){
            jButton8.setText(jButton5.getText());
            jButton8.setIcon(jButton5.getIcon());
            jButton5.setVisible(false);
            jButton8.setVisible(true);  
        }
        if(jButton6.isVisible()==false){
            jButton6.setText(jButton5.getText());
            jButton6.setIcon(jButton5.getIcon());
            jButton5.setVisible(false); 
            jButton6.setVisible(true);  
        }
        if(jButton4.isVisible()==false){
            jButton4.setText(jButton5.getText()); 
            jButton4.setIcon(jButton5.getIcon());
            jButton5.setVisible(false); 
            jButton4.setVisible(true); 
        }
        if(jButton2.isVisible()==false){
            jButton2.setText(jButton5.getText()); 
            jButton2.setIcon(jButton5.getIcon());
            jButton5.setVisible(false); 
            jButton2.setVisible(true); 
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jButton2.isVisible()==false){
            jButton2.setText(jButton3.getText()); 
            jButton2.setIcon(jButton3.getIcon());
            jButton3.setVisible(false);
            jButton2.setVisible(true);  
        }
        if(jButton6.isVisible()==false){
            jButton6.setText(jButton3.getText()); 
            jButton6.setIcon(jButton3.getIcon());
            jButton3.setVisible(false); 
            jButton6.setVisible(true);  
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jButton1.isVisible()==false){
            jButton1.setText(jButton2.getText()); 
            jButton1.setIcon(jButton2.getIcon());
            jButton2.setVisible(false); 
            jButton1.setVisible(true);  
        }
        if(jButton3.isVisible()==false){
            jButton3.setText(jButton2.getText()); 
            jButton3.setIcon(jButton2.getIcon());
            jButton2.setVisible(false); 
            jButton3.setVisible(true);  
        }
        if(jButton5.isVisible()==false){
            jButton5.setText(jButton2.getText()); 
            jButton5.setIcon(jButton2.getIcon());
            jButton2.setVisible(false); 
            jButton5.setVisible(true);  
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jButton4.isVisible()==false){
            jButton4.setText(jButton1.getText());
            jButton4.setIcon(jButton1.getIcon());
            jButton1.setVisible(false); 
            jButton4.setVisible(true); 
        }
        if(jButton2.isVisible()==false){
            jButton2.setText(jButton1.getText());
            jButton2.setIcon(jButton1.getIcon());
            jButton1.setVisible(false); 
            jButton2.setVisible(true);  
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jButton7.isVisible()==false){
            jButton7.setText(jButton4.getText());
            jButton7.setIcon(jButton4.getIcon());
            jButton4.setVisible(false); 
            jButton7.setVisible(true);  
        }
        if(jButton1.isVisible()==false){
            jButton1.setText(jButton4.getText());
            jButton1.setIcon(jButton4.getIcon());
            jButton4.setVisible(false); 
            jButton1.setVisible(true);  
        }
        if(jButton5.isVisible()==false){
            jButton5.setText(jButton4.getText()); 
            jButton5.setIcon(jButton4.getIcon());
            jButton4.setVisible(false); 
            jButton5.setVisible(true);  
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jButton8.isVisible()==false){
            jButton8.setText(jButton7.getText()); 
            jButton8.setIcon(jButton7.getIcon());
            jButton7.setVisible(false); 
            jButton8.setVisible(true);  
        }
        if(jButton4.isVisible()==false){
            jButton4.setText(jButton7.getText()); 
            jButton4.setIcon(jButton7.getIcon());
            jButton7.setVisible(false); 
            jButton4.setVisible(true);  
        }        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jButton1.setText("1");
        jButton2.setText("2");
        jButton3.setText("3");
        jButton4.setText("4");
        jButton5.setText("5");
        jButton6.setText("6");
        jButton7.setText("7");
        jButton8.setText("8");
        jButton9.setText("9");
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(false);
            
        jButton1.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile1.jpg")));
        jButton2.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile2.jpg")));
        jButton3.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile3.jpg")));
        jButton4.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile4.jpg")));
        jButton5.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile5.jpg")));
        jButton6.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile6.jpg")));
        jButton7.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile7.jpg")));
        jButton8.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile8.jpg")));
        jButton9.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile9.jpg")));
        puzzleDone();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        // TODO add your handling code here:
        jButton10.setForeground(Color.red);
        jButton10.setBackground(Color.blue);
        
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        // TODO add your handling code here:
        jButton10.setForeground(Color.blue);
        jButton10.setBackground(Color.gray);
    }//GEN-LAST:event_jButton10MouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

private void puzzleDone() {
       String b1=jButton1.getText();
       String b2=jButton2.getText();
       String b3=jButton3.getText();
       String b4=jButton4.getText();
       String b5=jButton5.getText();
       String b6=jButton6.getText();
       String b7=jButton7.getText();
       String b8=jButton8.getText();
       //String b9=btn9.getText();
       
       if(b1.equals("1")&&b2.equals("2")&&b3.equals("3")&&b4.equals("4")&&
          b5.equals("5")&&b6.equals("6")&&b7.equals("7")&&b8.equals("8")&&jButton9.isVisible()==false){
           JOptionPane.showMessageDialog(rootPane,"You completed the picture!! Here are some informations about the picture:");    
       }    
       
    }   
private void setIcons() {
    jButton1.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile1.jpg")));
    jButton2.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile2.jpg")));
    jButton3.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile3.jpg")));
    jButton4.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile4.jpg")));
    jButton5.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile5.jpg")));
    jButton6.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile6.jpg")));
    jButton7.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile7.jpg")));
    jButton8.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile8.jpg")));
    jButton9.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/Tile9.jpg")));
    jLabel2.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/mermaid.jpg")));
    jLabel3.setIcon(new  javax.swing.ImageIcon(this.getClass().getResource("../images/brand.jpg")));
    
}
    
}

